### PR TITLE
samples: exit early if no messages are returned

### LINKED ISSUE #189: sync pull causes DeadlineExceededException
doing a sync pull on a subscription, and if there is no message, it throws `DeadlineExceededException`.  Usually, if a pull times out, it would just return null.  Also, pull wait time interval is usually configuration, how can this be configured?

```
Caused by: com.google.api.gax.rpc.DeadlineExceededException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 4.978775875s. [buffered_nanos=291856840, buffered_nanos=331252614, remote_addr=pubsub.googleapis.com/172.217.12.138:443]
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:51)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1039)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1165)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:749)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:522)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:497)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$1CloseInContext.runInContext(ClientCallImpl.java:416)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	... 6 more
```

### PR DESCRIPTION
**Pull request by anguillanneuf**
Fixes #189 

The current samples will fail with `io.grpc.StatusRuntimeException: INVALID_ARGUMENT: You have not specified an ack ID in the request` if no messages are returned. Updating them to handle this case. 

This does not affect the existing tests for the samples.

I also noticed something that should not have been published with one of the samples in the first place - my project and topic ID. Apologies.

### CODE REVIEW

File: samples/snippets/src/main/java/pubsub/SubscribeSyncExample.java [hunk 1]
```diff
@@ -60,12 +60,20 @@ public static void subscribeSyncExample(
 
       // Use pullCallable().futureCall to asynchronously perform this operation.
       PullResponse pullResponse = subscriber.pullCallable().call(pullRequest);
+
+      // Exit the program if the pull response is empty.
+      if (pullResponse.getReceivedMessagesList().isEmpty()) {
+        System.out.println("No message was pulled. Exiting.");
+        System.exit(0);
```
Comment (kurtisvg) [inline samples/snippets/src/main/java/pubsub/SubscribeSyncExample.java:67]: System.exit probably isn't what you want here (it may crash the tests) - don't you just want to return?

File: samples/snippets/src/main/java/pubsub/SubscribeSyncWithLeaseExample.java [hunk 2]
```diff
@@ -68,8 +65,13 @@ public static void subscribeSyncWithLeaseExample(
       // Use pullCallable().futureCall to asynchronously perform this operation.
       PullResponse pullResponse = subscriber.pullCallable().call(pullRequest);
 
-      List<String> ackIds = new ArrayList<>();
+      // Exit the program if the pull response is empty.
+      if (pullResponse.getReceivedMessagesList().isEmpty()) {
+        System.out.println("No message was pulled. Exiting.");
+        System.exit(0);
```
Comment (kurtisvg) [inline samples/snippets/src/main/java/pubsub/SubscribeSyncWithLeaseExample.java:71]: same here

File: samples/snippets/src/main/java/pubsub/SubscribeSyncExample.java [hunk 3]
```diff
@@ -60,12 +60,20 @@ public static void subscribeSyncExample(
 
       // Use pullCallable().futureCall to asynchronously perform this operation.
       PullResponse pullResponse = subscriber.pullCallable().call(pullRequest);
+
+      // Exit the program if the pull response is empty.
```
Comment (kurtisvg) [inline samples/snippets/src/main/java/pubsub/SubscribeSyncExample.java:64]: This comment tells me _what_ you are doing (but so does the code). Can we update it to tell me _why_ we are doing?

**Review by kurtisvg — CHANGES_REQUESTED** [review]

File: samples/snippets/src/main/java/pubsub/SubscribeSyncExample.java (hunk 1 above)
Comment (anguillanneuf) [reply samples/snippets/src/main/java/pubsub/SubscribeSyncExample.java]: You're right. Updated to return.

File: samples/snippets/src/main/java/pubsub/SubscribeSyncWithLeaseExample.java (hunk 2 above)
Comment (anguillanneuf) [reply samples/snippets/src/main/java/pubsub/SubscribeSyncWithLeaseExample.java]: Done.

File: samples/snippets/src/main/java/pubsub/SubscribeSyncExample.java (hunk 3 above)
Comment (anguillanneuf) [reply samples/snippets/src/main/java/pubsub/SubscribeSyncExample.java]: That's a good point. Updated.

**Review by kurtisvg — APPROVED** [review]
