### PR TITLE
samples(testing): add retry rule

### LINKED ISSUE #552: pubsub.SchemaIT: testSchema failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: ed6b798c3908dfffe67a160d0cf38ef775081834
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/358403de-f6a3-4228-9f3a-5033f6c56e9f), [Sponge](http://sponge2/358403de-f6a3-4228-9f3a-5033f6c56e9f)
status: failed
<details><summary>Test output</summary><br><pre>com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: A service error has occurred. Please retry your request. If the error persists, please report it. [code=e8c0]
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:67)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1041)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1215)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:464)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:428)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:461)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.pubsub.v1.SchemaServiceClient.createSchema(SchemaServiceClient.java:264)
		at com.google.cloud.pubsub.v1.SchemaServiceClient.createSchema(SchemaServiceClient.java:203)
		at pubsub.CreateAvroSchemaExample.createAvroSchemaExample(CreateAvroSchemaExample.java:53)
		at pubsub.SchemaIT.testSchema(SchemaIT.java:121)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
		at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
		at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
		at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		... 1 more
Caused by: io.grpc.StatusRuntimeException: INTERNAL: A service error has occurred. Please retry your request. If the error persists, please report it. [code=e8c0]
	at io.grpc.Status.asRuntimeException(Status.java:535)
	... 17 more
</pre></details>

### PR DESCRIPTION
**Pull request by anguillanneuf**
Fixes #552 

I referenced: https://www.lenar.io/how-to-re-run-failed-tests-junit/

~Alternatively, upgrade to `junit5` and use `@RepeatedTest annotation`: https://www.swtestacademy.com/junit-5-how-to-repeat-failed-test/~ ← Not super useful because it retries successful runs. 

Also tried 

```xml
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-core</artifactId>
      <version>1.94.3</version>
    </dependency>
```

But unable to `import com.google.cloud.testing.junit4.MultipleAttemptsRule;`

Turned out that I need `<classifier>tests</classifier>` tag.

### CODE REVIEW

File: samples/snippets/src/test/java/pubsub/Retry.java [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package pubsub;
+
+import java.lang.annotation.Retention;
+import java.lang.annotation.RetentionPolicy;
+
+@Retention(RetentionPolicy.RUNTIME)
```
Comment (kolea2) [inline samples/snippets/src/test/java/pubsub/Retry.java:22]: @BenWhitehead could we use the junit rules you wrote here?

Comment (anguillanneuf) [reply samples/snippets/src/test/java/pubsub/Retry.java:22]: junit5 has a @RepeatedTest annotation if we can upgrade?

Comment (kolea2) [reply samples/snippets/src/test/java/pubsub/Retry.java:22]: Sorry, let me clarify here :) @BenWhitehead worked on some shared JUnit rules in java-core, wondering if we can make use of them - https://github.com/googleapis/java-core/pull/327/files. @anguillanneuf let me know if these are a good fit for what you're trying to accomplish, otherwise feel free to ignore my suggestion :)

Comment (anguillanneuf) [reply samples/snippets/src/test/java/pubsub/Retry.java:22]: https://github.com/googleapis/java-core/blob/master/google-cloud-core/src/test/java/com/google/cloud/testing/junit4/MultipleAttemptsRule.java is what I need, but it's in `src/test/`, is that something I can import?

Do you know if we can use the this for testing?
```xml
 <dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-engine</artifactId>
    <version>5.7.1</version>
    <scope>test</scope>
</dependency>
```

File: samples/snippets/src/test/java/pubsub/SchemaIT.java [hunk 2]
```diff
@@ -73,12 +73,8 @@ private static void requireEnvVar(String varName) {
         System.getenv(varName));
   }
 
-  @Rule public Timeout globalTimeout = Timeout.seconds(300); // 5 minute timeout
-
-  @BeforeClass
```
Comment (kolea2) [inline samples/snippets/src/test/java/pubsub/SchemaIT.java:78]: is this no longer needed?

Comment (anguillanneuf) [reply samples/snippets/src/test/java/pubsub/SchemaIT.java:78]: Oops, I think I deleted these by accident.
