### PR TITLE
fix: Prevent excessive string parsing when publishing and receiving messages to improve performance

### LINKED ISSUE #2295: Potential (CPU) performance improvement when publishing
I was profiling a pubsub benchmark and I saw a potential improvement. Each publish it parses the topicName. 90% of publish CPU time is spent on this. 30% of total CPU during my profiling. One could lift this up into the publisher and pass `TopicName` directly into `PubsubMessageWrapper` in the `publish`

image

Short Repro

```kt
val sessionSampleMsg = """{"website":"https://minty-modernist.name","domain":"limp-effector.com","job":{"title":"Investor Creative Administrator","descriptor":"Customer","area":"Accountability","type":"Consultant","company":"Bailey - Ledner"},"uuid":"1ef60952-c540-47ad-97c3-e923e20faafc","objectId":"67643b6bac95a0492808f66b"}"""

val samplePubsubMsg = PubsubMessage.newBuilder()
    .setData(ByteString.copyFromUtf8(sessionSampleMsg))
    .build()

val testTopic = "projects/test/topics/pst-test"
val optimalPublisher = Publisher.newBuilder(testTopic)

fun startProducing(publisher: Publisher) {
    while (true){
        publisher.publish(samplePubsubMsg)
    }
}

fun main() {
  startProducing(optimalPublisher)
}

```

Profile background

_Was run on 2vpcu xeon + 4GB ram, LTS JDK 21_

I have included the profile, see below
[optimal-producer.zip](https://github.com/user-attachments/files/18199774/optimal-producer.zip)

### PR DESCRIPTION
**Pull request by michaelpri10**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-pubsub/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #2295  ☕️

Based off of PR #2304, which some added changes to the subscribe path.

### CODE REVIEW

**Comment by MV-GH** [comment]
Thanks for taking this up. I believe `OpenTelemetryPubsubTracer.startPublishRpcSpan` would also benefit from a similar change.

File: google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java [hunk 1]
```diff
@@ -105,6 +106,7 @@ class MessageDispatcher {
   private final Distribution ackLatencyDistribution;
 
   private final String subscriptionName;
+  private final SubscriptionName subscriptionNameObject;
```
Comment (hongalex) [inline google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java:109]: How does this new object interact with the previous `subscriptionName` string? Is the latter still necessary?

**Comment by michaelpri10** [comment]
@hongalex Gentle bump on this.

**Comment by michaelpri10** [comment]
@hongalex Friendly bump on this PR.

**Review by lahuang4 — APPROVED** [review]
