### PR TITLE
fix: ensure proper cleanup of publisher in tests

### LINKED ISSUE #309: Client library tests taking too long to complete
The client library tests are taking a long time to complete - a Kokoro Integration Test timed out when running the presubmit checks before submitting a PR.  The tests did not always take this long to complete, we should look into this.

### PR DESCRIPTION
**Pull request by hannahrogers-google**
Our PublisherImplTest is taking over 5 minutes to run because we are not properly shutting down the publisher/testChannel.  This PR ensures everything is shutdown properly, and decreases the test time to 10 seconds. Additional details provided in #309.

Fixes #309  ☕️

### CODE REVIEW

File: google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java [hunk 1]
```diff
@@ -1115,7 +1126,14 @@ public void run() {
...
         .setExecutorProvider(FixedExecutorProvider.create(fakeExecutor))
-        .setChannelProvider(TEST_CHANNEL_PROVIDER)
+        .setChannelProvider(
+            FixedTransportChannelProvider.create(GrpcTransportChannel.create(testChannel)))
         .setCredentialsProvider(NoCredentialsProvider.create());
   }
+
+  private void shutdownTestPublisher(Publisher publisher) throws InterruptedException {
+    publisher.shutdown();
+    fakeExecutor.advanceTime(Duration.ofSeconds(10));
```
Comment (hongalex) [inline google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java:1136]: How was 10 seconds chosen? Specifically, how long does this test need to execute on average?

Comment (hannahrogers-google) [reply google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java:1136]: The gax layer implements a Watchdog (https://github.com/googleapis/gax-java/blob/master/gax/src/main/java/com/google/api/gax/rpc/Watchdog.java) that periodically garbage collects idle streams. The check is scheduled at a fixed rate every 10 seconds.  So, I chose 10 seconds to ensure that the watchdog check completes, otherwise we have to wait the full timeout.
