### PR TITLE
fix: Fixing the shutdown logic for streaming subscriber connection

### LINKED ISSUE #1544: Shutdown order seems to be backwards
The [`doStop` method for StreamingSubscriberClient](https://github.com/googleapis/java-pubsub/blob/c1d62b00c92a77b6782f06bca229f10b8f603825/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java#L193-L203) seems like it may be the opposite order of what would allow it to shut down most quickly and cleanly. It first calls `runShutdown()`, which calls `messageDispatcher.stop();`. That method waits until there are [no outstanding messages](https://github.com/googleapis/java-pubsub/blob/c1d62b00c92a77b6782f06bca229f10b8f603825/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java#L279). How do we ensure that no new messages come in? If they do, we could seemingly end up in a state where the client can never shut down because more messages come in constantly.

We should see if this can happen and if so, consider changing the order in which we do the shutdown so we do `clientStream.closeSendWithError(Status.CANCELLED.asException());` first.

### PR DESCRIPTION
**Pull request by maitrimangal**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-pubsub/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #1544

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

### CODE REVIEW

**Review by hannahrogers-google — CHANGES_REQUESTED** [review]
~~I don't think we can do this. In runShutdown(), we call ackOperationsWaiter.waitComplete(). Which waits for all outstanding acks to be sent on the clientStream. If we close the clientStream before calling runShutdown, all remaining acks will all fail with the CancelledException.~~

Nevermind - I was thinking it was the stub we were shutting down. Shutting down the clientStream should be ok

File: google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java [hunk 1]
```diff
@@ -191,15 +191,14 @@ protected void doStart() {
...
-    runShutdown();
-
     lock.lock();
     try {
       clientStream.closeSendWithError(Status.CANCELLED.asException());
     } finally {
       lock.unlock();
       notifyStopped();
     }
+    runShutdown();
```
Comment (hannahrogers-google) [inline google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java:201]: We don't want to notifyStopped() until runShutdown() has completed because this has a lot of blocking work.

Comment (maitrimangal) [reply google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java:200]: Done. This is the order now:
1. Close stream
2. Wait for message dispatcher to complete (dispatch message to end user, and wait for ack from end user)
3. Wait for ack operations to complete (send ack to pubsub)
4. notifyStop
